マイページに観戦ヒートマップを実装しました。
dustium162/footlog-frontend pull request #28
Opened 2022-04-23 01:24 UTC by amount86

#6 close

2022-04-25 14:18 UTC, dustium162 requested changes
PRありがとうございます！
モーダルのタイトルのところが修正できたらあとは大丈夫だと思います！
APIのPRにもレビューしてあるので、そちらの反映も良ければお願いします。
今回はデプロイを同時にやらないとバグる気がするので、そのあたりは相談しましょう！

2022-04-25 14:22 UTC, dustium162 requested changes
APIのPRに対応するレビューを忘れていたので追加しました。

2022-04-25 14:22 UTC, dustium162 commented on src/components/Heatmap.js
> +    axios.get(`${process.env.REACT_APP_API_ENDPOINT}/users/${userId}/first_post_season`,
APIのPRに書いたのですが、`first_post_season`を`first-post-season`にしたら良いかなと思います。
意見などあればぜひ！

2022-05-07 03:41 UTC, amount86 commented on src/components/Heatmap.js
> +    axios.get(`${process.env.REACT_APP_API_ENDPOINT}/users/${userId}/first_post_season`,
了解しました。

2022-05-07 03:49 UTC, amount86 commented on src/components/HeatmapBox.js
> +          <Modal.Title>投稿の編集</Modal.Title>
了解しました。

2022-05-07 03:53 UTC, dustium162 approved these changes
お疲れさまでした！！
マージしましょう！
![LGTM](https://image.lgtmoon.dev/29073)

2022-05-07 03:55 UTC, merged